import { Tier, Status } from './tier';
import ffi = require('ffi');

/**
 * Malloc tier (Linux only)
 * Main resources used: Memory
 */
export default class Malloc extends Tier {

  bytes: number;
  constructor(bytes = 500000){
    super();
    this.bytes = bytes;
  }
  
  /**
   * It executes a C lib that execute several malloc, calloc, realloc and free operations. 
   * Check file malloc.c for details.
   * The libmalloc is generated by executing: npm run gulp
   * @param allocation quantity of bytes to be allocate in each iteration.
   */
  protected executeTask(): Status {
    var libmalloc = ffi.Library('./dist/clib/libmalloc', {
      'stressMalloc': [ 'int', [ 'long' ] ]
    });
    
    var output = libmalloc.stressMalloc(this.bytes);
    if(output == -1)
      return new Status("There was an error executing the malloc lib.", 500);
    return new Status("Malloc lib executed successfully.");
  }
}